### ISSUE TITLE
STEP files

### ISSUE THREAD

**Issue by Titi9237** [piotrwest/TheUltimateCloudCatFeeder-3DModels#1]
Hi @piotrwest,

Would it be possible to have access to the STEP files from your cat feeder ? I would like to do some minor modification to improve printing performances (limiting/removing supports).

Great design by the way !

Thanks

**Comment by piotrwest** [comment]
Hi, of course!

I've added the export in whatever formats I could find in the export options, including STEP. Also, I've exported a new version with much better looking food container. Find everything here: https://github.com/piotrwest/TheUltimateCloudCatFeeder-3DModels/tree/master/Export%20(v183)

Feel free to drop me message/email/issue with photo of your build!

**Comment by Titi9237** [comment]
Thanks !
